### ISSUE TITLE
[BUG] Plantage lors de la syncronisation des abonnements

### ISSUE THREAD

**Issue by Kyrela** [Androz2091/vinted-discord-bot#13]
Le bot marchait parfaitement jusqu'à que j'y ajoute des abonnements. Maintenant, il plante dès le lancement.
Voici l'erreure levée :

```
🔗 Connecté sur le compte de Lunar Cook Vinted Monitor#6583 !

🤖 Synchronisation à Vinted...

/home/pi/vinted-discord-bot-main/node_modules/vinted-api/index.js:37
    for (let param of params) {
                      ^

TypeError: params is not iterable
    at parseVintedURL (/home/pi/vinted-discord-bot-main/node_modules/vinted-api/index.js:37:23)
    at /home/pi/vinted-discord-bot-main/node_modules/vinted-api/index.js:74:41
    at new Promise (<anonymous>)
    at Object.search (/home/pi/vinted-discord-bot-main/node_modules/vinted-api/index.js:72:12)
    at /home/pi/vinted-discord-bot-main/index.js:63:16
    at new Promise (<anonymous>)
    at syncSubscription (/home/pi/vinted-discord-bot-main/index.js:61:12)
    at /home/pi/vinted-discord-bot-main/index.js:138:49
    at Array.map (<anonymous>)
    at sync (/home/pi/vinted-discord-bot-main/index.js:138:36)

Node.js v17.2.0
```

Je peux fournir autant d'informations qu'il sera nécessaire, si celle-ci ne suffit pas.

Merci d'avance !

**Comment by Androz2091** [comment]
réglé 👍
