### ISSUE TITLE
Fetching Cookie -- :/

### ISSUE THREAD

**Issue by darkblink** [Androz2091/vinted-discord-bot#2]
Hi there, on OSX Macintosh, I tried to launch vinted discord bot.

Unfortunately after selecting all my options, this line appear : `Search returned an error. Promise resolved. Can not fetch cookie`

Is there a solution to this problem ? Or Macintosh is completely trash for this bot ?

TY

**Comment by Androz2091** [comment]
Hey. I'm using MacOS (Big Sur with the m1 ship), and it works perfectly. What you can do is to run the following commands:
* `npm uninstall vinted-api`
* `npm install Androz2091/vinted-api#debug`
* then restart the bot

You should see more logs in the console

**Comment by darkblink** [comment]
Thanks for your fast repl, here i Got :

```
 ReferenceError: AbortController is not defined
    at /Users/hugofrion/Downloads/vinted-discord-bot-main/node_modules/vinted-api/index.js:11:28
    at new Promise (<anonymous>)
    at fetchCookie (/Users/hugofrion/Downloads/vinted-discord-bot-main/node_modules/vinted-api/index.js:10:12)
    at /Users/hugofrion/Downloads/vinted-discord-bot-main/node_modules/vinted-api/index.js:36:9
    at new Promise (<anonymous>)
    at Object.search (/Users/hugofrion/Downloads/vinted-discord-bot-main/node_modules/vinted-api/index.js:29:12)
    at /Users/hugofrion/Downloads/vinted-discord-bot-main/index.js:18:16
    at new Promise (<anonymous>)
    at syncSubscription (/Users/hugofrion/Downloads/vinted-discord-bot-main/index.js:15:12)
    at /Users/hugofrion/Downloads/vinted-discord-bot-main/index.js:77:49
```

**Comment by Androz2091** [comment]
All right, so this is because you don't have the latest version of Node.js on your computer. I think that abort controllers were added with Node v15. Try to download and install it and the bot should work properly :wink:
