### ISSUE TITLE
params is not iterable

### ISSUE THREAD

**Issue by Blacktime2** [Androz2091/vinted-discord-bot#34]
Après avoir configuré le BOT j'obtiens ce message d'erreur :

`Search returned an error. Promise resolved. TypeError: params is not iterable
    at getVintedQuerystring (C:\Users\Administrateur.SERVEURTIM\Documents\BV\node_modules\vinted-api\index.js:31:23)
    at C:\Users\Administrateur.SERVEURTIM\Documents\BV\node_modules\vinted-api\index.js:63:24
    at new Promise (<anonymous>)
    at Object.search (C:\Users\Administrateur.SERVEURTIM\Documents\BV\node_modules\vinted-api\index.js:61:12)
    at C:\Users\Administrateur.SERVEURTIM\Documents\BV\index.js:62:16
    at new Promise (<anonymous>)
    at syncSubscription (C:\Users\Administrateur.SERVEURTIM\Documents\BV\index.js:61:12)
    at C:\Users\Administrateur.SERVEURTIM\Documents\BV\index.js:133:49
    at Array.map (<anonymous>)
    at Timeout.sync [as _onTimeout] (C:\Users\Administrateur.SERVEURTIM\Documents\BV\index.js:133:36)`

Une idée ?
Merci à tous ceux qui prendrons le temps de me répondre !

**Comment by Blacktime2** [comment]
Le message d'erreur après dès qu'il détecte un nouvel élément (nouveau vêtement).

**Comment by gab123righ** [comment]
salut je ne peux pas te répondre mais peux tu me guider sur l'installation je comprends rien

**Comment by Blacktime2** [comment]
> salut je ne peux pas te répondre mais peux tu me guider sur l'installation je comprends rien

Je crois que j'ai dû suivre ce tuto pour y arriver : https://www.youtube.com/watch?v=uRh4cnfuiPk&ab_channel=Shoneo
Mais du coup je suis bloqué sur mon message d'erreur. Après j'ai test un autre bot qui est bcp plus simple à mettre en œuvre et est gratuit et très actif : https://www.youtube.com/watch?v=eaStcisD9ow&ab_channel=2spy
